version = 1

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "php"
enabled = true